name: mca_web_2022_07
description: MCA App.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #Local packages
  pluto_grid:
    path: ./pluto_grid
  simpleicons:
    path: ./simpleicons

  syncfusion_flutter_calendar:
    path: ./syncfusion_flutter_calendar-20.2.43

  #External packages
  google_maps_webservice:
    git:
      url: https://github.com/YakivGalkin/google_maps_webservice

  google_maps_flutter: ^2.2.1
  google_maps_flutter_web: ^0.4.0+3
  google_maps_widget: ^1.0.5+1

  flutter_easylogger: ^2.3.3
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  auto_route: ^4.2.1
  intl: ^0.17.0
  dropdown_button2: 1.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  responsive_framework: ^0.2.0
  mix: ^0.0.6
  collection: ^1.16.0
  image_picker: ^0.8.5+3
  get: ^4.6.5
  dotted_border: ^2.0.0+3
  talker_flutter: ^2.2.1
  syncfusion_flutter_datepicker: ^20.4.48
  month_year_picker: ^0.2.0+3
  adaptive_scrollbar: ^2.1.2
  get_ip_address: ^0.0.5
  plural_noun: ^0.1.2
  fingerprintjs: ^2.0.0
  flutter_svg: ^1.1.6
  easy_loading_button: ^0.3.2
  bot_toast: ^4.0.4
  select2dot1: ^2.0.7
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.2
  auto_route_generator: ^4.2.0
  retrofit_generator: ^4.0.3
  json_serializable: ^6.3.1
  hive_generator: ^1.1.3

dependency_overrides:
  retrofit: 3.0.2
  syncfusion_flutter_datepicker: "20.2.43"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/NunitoSans-Bold.ttf

    - family: Light
      fonts:
        - asset: assets/fonts/NunitoSans-Light.ttf

    - family: Regular
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
