name: mca_web_2022_07
description: MCA App.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #Local packages
  pluto_grid:
    path: ./pluto_grid
  simpleicons:
    path: ./simpleicons
  draggable_grid:
    path: ./draggable_grid

  #External packages
  google_maps_webservice:
    git:
      url: https://github.com/YakivGalkin/google_maps_webservice

  #pub.dev packages
  google_maps_flutter: ^2.2.1
  google_maps_flutter_web: ^0.4.0+3
  google_maps_widget: ^1.0.5+1

  cupertino_icons: ^1.0.2
  flutter_easylogger: ^2.3.3
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  auto_route: ^4.2.1
  intl: ^0.17.0
  dropdown_button2: ^1.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  responsive_framework: ^0.2.0
  mix: ^0.0.6
  collection: ^1.16.0
  image_picker: ^0.8.5+3
  faker: ^2.0.0
  geolocator: ^9.0.2
  get: ^4.6.5
  dart_ipify: ^1.1.1
  dotted_border: ^2.0.0+3
  talker_flutter: ^2.2.1
  public_suffix: ^3.0.0
  flutter_screenutil: ^5.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.2
  auto_route_generator: ^4.2.0
  retrofit_generator: ^4.0.3
  json_serializable: ^6.3.1
  hive_generator: ^1.1.3

#First configure flutter_intl
flutter_intl:
  enabled: true
  class_name: "AppIntl" # Class name which is used in by the client, default "S"
  arb_dir: "lib/l10n" # .arb files located dir, default 'lib/l10n'
  main_locale: "en" # main locale, default "en"
  output_dir: "lib/intl_conf/intl" # Generated i10n files location

dependency_overrides:
  retrofit: 3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/NunitoSans-Bold.ttf

    - family: Light
      fonts:
        - asset: assets/fonts/NunitoSans-Light.ttf

    - family: Regular
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
