name: simpleicons
description: simpleicons set of SVG icons in your Flutter app.
version: 0.4.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.1+1
  path: ^1.8.1

dev_dependencies:
  code_builder: ^4.2.0
  dart_style: ^2.2.3
  recase: ^4.0.0

flutter:
  assets:
    - assets/
    - assets/icons/

