// Mocks generated by Mockito 5.4.2 from annotations
// in mca_dashboard/test/rest_api_test/lists_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mca_dashboard/manager/api/rest_client.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpResponse_0<T> extends _i1.SmartFake
    implements _i2.HttpResponse<T> {
  _FakeHttpResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i3.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getAccessToken(
    String? grantType,
    String? domain,
    String? clientId,
    String? clientSecret,
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [
            grantType,
            domain,
            clientId,
            clientSecret,
            username,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getAccessToken,
            [
              grantType,
              domain,
              clientId,
              clientSecret,
              username,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getRefreshToken(
    String? grantType,
    String? refreshToken,
    String? clientId,
    String? clientSecret,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [
            grantType,
            refreshToken,
            clientId,
            clientSecret,
          ],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getRefreshToken,
            [
              grantType,
              refreshToken,
              clientId,
              clientSecret,
            ],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getFormats() => (super.noSuchMethod(
        Invocation.method(
          #getFormats,
          [],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getFormats,
            [],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getUsers() => (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getUsers,
            [],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getLists() => (super.noSuchMethod(
        Invocation.method(
          #getLists,
          [],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getLists,
            [],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getUserDetails(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserDetails,
          [userId],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getUserDetails,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getUserDetailsReviews(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserDetailsReviews,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getUserDetailsReviews,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteUserDetailsReviews(
    String? id,
    int? reviewid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserDetailsReviews,
          [
            id,
            reviewid,
          ],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteUserDetailsReviews,
            [
              id,
              reviewid,
            ],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postUserDetailsReviews(
    String? id, {
    required String? title,
    required String? date,
    required int? conductedBy,
    int? reviewid,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUserDetailsReviews,
          [id],
          {
            #title: title,
            #date: date,
            #conductedBy: conductedBy,
            #reviewid: reviewid,
            #notes: notes,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postUserDetailsReviews,
            [id],
            {
              #title: title,
              #date: date,
              #conductedBy: conductedBy,
              #reviewid: reviewid,
              #notes: notes,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getUserDetailsPhotos(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserDetailsPhotos,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getUserDetailsPhotos,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getUserDetailsContracts(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserDetailsContracts,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getUserDetailsContracts,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postUserDetailsContracts(
    String? id, {
    required String? csd,
    required int? contractType,
    required int? hct,
    required int? AHEonYS,
    required int? awh,
    required int? jobTitle,
    required String? wdpw,
    double? salaryPH,
    int? contractid,
    String? ced,
    String? initHolidays,
    String? jobDescription,
    double? salaryPA,
    double? salaryOT,
    int? ahe,
    String? lunchtime,
    String? lunchtimeUnpaid,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUserDetailsContracts,
          [id],
          {
            #csd: csd,
            #contractType: contractType,
            #hct: hct,
            #AHEonYS: AHEonYS,
            #awh: awh,
            #jobTitle: jobTitle,
            #wdpw: wdpw,
            #salaryPH: salaryPH,
            #contractid: contractid,
            #ced: ced,
            #initHolidays: initHolidays,
            #jobDescription: jobDescription,
            #salaryPA: salaryPA,
            #salaryOT: salaryOT,
            #ahe: ahe,
            #lunchtime: lunchtime,
            #lunchtimeUnpaid: lunchtimeUnpaid,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postUserDetailsContracts,
            [id],
            {
              #csd: csd,
              #contractType: contractType,
              #hct: hct,
              #AHEonYS: AHEonYS,
              #awh: awh,
              #jobTitle: jobTitle,
              #wdpw: wdpw,
              #salaryPH: salaryPH,
              #contractid: contractid,
              #ced: ced,
              #initHolidays: initHolidays,
              #jobDescription: jobDescription,
              #salaryPA: salaryPA,
              #salaryOT: salaryOT,
              #ahe: ahe,
              #lunchtime: lunchtime,
              #lunchtimeUnpaid: lunchtimeUnpaid,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteUserDetailsContract(
    String? id,
    int? contractid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserDetailsContract,
          [
            id,
            contractid,
          ],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteUserDetailsContract,
            [
              id,
              contractid,
            ],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getUserDetailsVisas(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserDetailsVisas,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getUserDetailsVisas,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postUserDetailsVisa(
    String? id, {
    required String? documentNo,
    required String? startDate,
    required String? endDate,
    required int? notExpire,
    required int? visaTypeId,
    int? visaid,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUserDetailsVisa,
          [id],
          {
            #documentNo: documentNo,
            #startDate: startDate,
            #endDate: endDate,
            #notExpire: notExpire,
            #visaTypeId: visaTypeId,
            #visaid: visaid,
            #notes: notes,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postUserDetailsVisa,
            [id],
            {
              #documentNo: documentNo,
              #startDate: startDate,
              #endDate: endDate,
              #notExpire: notExpire,
              #visaTypeId: visaTypeId,
              #visaid: visaid,
              #notes: notes,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteUserDetailsVisa(
    String? id,
    String? visaid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserDetailsVisa,
          [
            id,
            visaid,
          ],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteUserDetailsVisa,
            [
              id,
              visaid,
            ],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getUserDetailsPreferredShifts(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserDetailsPreferredShifts,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getUserDetailsPreferredShifts,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postUserDetailsPreferredShift(
    String? id, {
    required int? weekId,
    required int? dayId,
    required int? shiftId,
    int? timingid,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUserDetailsPreferredShift,
          [id],
          {
            #weekId: weekId,
            #dayId: dayId,
            #shiftId: shiftId,
            #timingid: timingid,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postUserDetailsPreferredShift,
            [id],
            {
              #weekId: weekId,
              #dayId: dayId,
              #shiftId: shiftId,
              #timingid: timingid,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteUserDetailsPreferredShift(
    String? id,
    int? timingid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserDetailsPreferredShift,
          [
            id,
            timingid,
          ],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteUserDetailsPreferredShift,
            [
              id,
              timingid,
            ],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getUserDetailsQualifications(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserDetailsQualifications,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getUserDetailsQualifications,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postUserDetailsQualifs(
    String? id, {
    int? userqualificationid,
    required int? qualificationId,
    required int? levelId,
    required String? achievementDate,
    String? expiryDate,
    required String? certificateNumber,
    String? comments,
    String? file,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUserDetailsQualifs,
          [id],
          {
            #userqualificationid: userqualificationid,
            #qualificationId: qualificationId,
            #levelId: levelId,
            #achievementDate: achievementDate,
            #expiryDate: expiryDate,
            #certificateNumber: certificateNumber,
            #comments: comments,
            #file: file,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postUserDetailsQualifs,
            [id],
            {
              #userqualificationid: userqualificationid,
              #qualificationId: qualificationId,
              #levelId: levelId,
              #achievementDate: achievementDate,
              #expiryDate: expiryDate,
              #certificateNumber: certificateNumber,
              #comments: comments,
              #file: file,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteUserDetailsQualifs(
    String? id,
    int? userqualificationid,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserDetailsQualifs,
          [
            id,
            userqualificationid,
          ],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteUserDetailsQualifs,
            [
              id,
              userqualificationid,
            ],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getUserDetailsMobile(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserDetailsMobile,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getUserDetailsMobile,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteUserDetailsMobile(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserDetailsMobile,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteUserDetailsMobile,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getUserDetailsStatus(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserDetailsStatus,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getUserDetailsStatus,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postUserDetailsStatus(
    String? id, {
    required String? status,
    required String? shift,
    required String? location,
    String? comment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUserDetailsStatus,
          [id],
          {
            #status: status,
            #shift: shift,
            #location: location,
            #comment: comment,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postUserDetailsStatus,
            [id],
            {
              #status: status,
              #shift: shift,
              #location: location,
              #comment: comment,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getLocation(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocation,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getLocation,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getStorageItems(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStorageItems,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getStorageItems,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getClients(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClients,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getClients,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getProperties(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProperties,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getProperties,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getQuotes(
    String? id, {
    String? date,
    int? location_id,
    int? shift_id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuotes,
          [id],
          {
            #date: date,
            #location_id: location_id,
            #shift_id: shift_id,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getQuotes,
            [id],
            {
              #date: date,
              #location_id: location_id,
              #shift_id: shift_id,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getWarehouses() => (super.noSuchMethod(
        Invocation.method(
          #getWarehouses,
          [],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getWarehouses,
            [],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getCompanyInfo() => (super.noSuchMethod(
        Invocation.method(
          #getCompanyInfo,
          [],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getCompanyInfo,
            [],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getAllocations(
    String? date,
    int? locationId,
    int? userId,
    int? shiftId, {
    String? until,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllocations,
          [
            date,
            locationId,
            userId,
            shiftId,
          ],
          {#until: until},
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getAllocations,
            [
              date,
              locationId,
              userId,
              shiftId,
            ],
            {#until: until},
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postAllocation(
    int? locationId,
    int? userId,
    int? shiftId,
    String? date,
    String? action, {
    String? date_until,
    String? target_date,
    int? target_location,
    int? target_user,
    int? target_shift,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postAllocation,
          [
            locationId,
            userId,
            shiftId,
            date,
            action,
          ],
          {
            #date_until: date_until,
            #target_date: target_date,
            #target_location: target_location,
            #target_user: target_user,
            #target_shift: target_shift,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postAllocation,
            [
              locationId,
              userId,
              shiftId,
              date,
              action,
            ],
            {
              #date_until: date_until,
              #target_date: target_date,
              #target_location: target_location,
              #target_user: target_user,
              #target_shift: target_shift,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getUnavailableUserList(String? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnavailableUserList,
          [date],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getUnavailableUserList,
            [date],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postStorageItem({
    int? id,
    required String? name,
    required int? taxId,
    String? incomingPrice,
    String? outgoingPrice,
    required bool? service,
    required bool? active,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postStorageItem,
          [],
          {
            #id: id,
            #name: name,
            #taxId: taxId,
            #incomingPrice: incomingPrice,
            #outgoingPrice: outgoingPrice,
            #service: service,
            #active: active,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postStorageItem,
            [],
            {
              #id: id,
              #name: name,
              #taxId: taxId,
              #incomingPrice: incomingPrice,
              #outgoingPrice: outgoingPrice,
              #service: service,
              #active: active,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postLocation({
    int? id,
    required String? name,
    required bool? active,
    required bool? base,
    required bool? timelimit,
    required String? latitude,
    required String? longitude,
    required String? radius,
    String? phoneLandline,
    String? phoneMobile,
    String? phoneFax,
    String? email,
    required bool? sendChecklist,
    required bool? anywhere,
    String? addressLine1,
    String? addressLine2,
    String? addressCity,
    String? addressCounty,
    String? addressCountry,
    String? addressPostcode,
    required bool? fixedipaddress,
    String? ipaddress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postLocation,
          [],
          {
            #id: id,
            #name: name,
            #active: active,
            #base: base,
            #timelimit: timelimit,
            #latitude: latitude,
            #longitude: longitude,
            #radius: radius,
            #phoneLandline: phoneLandline,
            #phoneMobile: phoneMobile,
            #phoneFax: phoneFax,
            #email: email,
            #sendChecklist: sendChecklist,
            #anywhere: anywhere,
            #addressLine1: addressLine1,
            #addressLine2: addressLine2,
            #addressCity: addressCity,
            #addressCounty: addressCounty,
            #addressCountry: addressCountry,
            #addressPostcode: addressPostcode,
            #fixedipaddress: fixedipaddress,
            #ipaddress: ipaddress,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postLocation,
            [],
            {
              #id: id,
              #name: name,
              #active: active,
              #base: base,
              #timelimit: timelimit,
              #latitude: latitude,
              #longitude: longitude,
              #radius: radius,
              #phoneLandline: phoneLandline,
              #phoneMobile: phoneMobile,
              #phoneFax: phoneFax,
              #email: email,
              #sendChecklist: sendChecklist,
              #anywhere: anywhere,
              #addressLine1: addressLine1,
              #addressLine2: addressLine2,
              #addressCity: addressCity,
              #addressCounty: addressCounty,
              #addressCountry: addressCountry,
              #addressPostcode: addressPostcode,
              #fixedipaddress: fixedipaddress,
              #ipaddress: ipaddress,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postClient(
    int? id, {
    required String? name,
    required String? company,
    required String? phone,
    required String? email,
    required String? addressLine1,
    required String? addressCity,
    required String? addressPostcode,
    required String? addressCountry,
    String? notes,
    required int? currencyId,
    required int? paymentMethodId,
    required int? payingDays,
    required bool? active,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postClient,
          [id],
          {
            #name: name,
            #company: company,
            #phone: phone,
            #email: email,
            #addressLine1: addressLine1,
            #addressCity: addressCity,
            #addressPostcode: addressPostcode,
            #addressCountry: addressCountry,
            #notes: notes,
            #currencyId: currencyId,
            #paymentMethodId: paymentMethodId,
            #payingDays: payingDays,
            #active: active,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postClient,
            [id],
            {
              #name: name,
              #company: company,
              #phone: phone,
              #email: email,
              #addressLine1: addressLine1,
              #addressCity: addressCity,
              #addressPostcode: addressPostcode,
              #addressCountry: addressCountry,
              #notes: notes,
              #currencyId: currencyId,
              #paymentMethodId: paymentMethodId,
              #payingDays: payingDays,
              #active: active,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> changeQuoteStatus(
    int? id, {
    required String? status,
    required String? ip_address,
    required String? browser,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeQuoteStatus,
          [id],
          {
            #status: status,
            #ip_address: ip_address,
            #browser: browser,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #changeQuoteStatus,
            [id],
            {
              #status: status,
              #ip_address: ip_address,
              #browser: browser,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> sendEmailToQuote(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmailToQuote,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #sendEmailToQuote,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getClientContractItems(
    int? clientId,
    int? shiftId,
    String? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClientContractItems,
          [
            clientId,
            shiftId,
            date,
          ],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getClientContractItems,
            [
              clientId,
              shiftId,
              date,
            ],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getPropertyDetails(int? shiftId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPropertyDetails,
          [shiftId],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getPropertyDetails,
            [shiftId],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> updatePropertyDetails(
    int? shiftId, {
    required int? bedrooms,
    required int? bathrooms,
    required int? min_sleeps,
    required int? max_sleeps,
    required String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePropertyDetails,
          [shiftId],
          {
            #bedrooms: bedrooms,
            #bathrooms: bathrooms,
            #min_sleeps: min_sleeps,
            #max_sleeps: max_sleeps,
            #notes: notes,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #updatePropertyDetails,
            [shiftId],
            {
              #bedrooms: bedrooms,
              #bathrooms: bathrooms,
              #min_sleeps: min_sleeps,
              #max_sleeps: max_sleeps,
              #notes: notes,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postUserDetails(
    int? userId, {
    required String? firstName,
    required String? lastName,
    required String? addressLine1,
    required String? addressCity,
    required String? addressPostcode,
    int? group,
    int? location,
    required String? role,
    String? language,
    String? upass,
    String? title,
    String? birthday,
    String? nationality,
    int? religion,
    int? ethnic,
    String? maritalStatus,
    String? ni,
    String? phoneLandline,
    String? phoneMobile,
    String? nokName,
    String? nokPhone,
    String? nokRelation,
    String? addressLine2,
    String? addressCounty,
    String? addressCountry,
    String? payrolCode,
    String? notes,
    String? isActive,
    int? exEmail,
    double? latitude,
    double? longitude,
    String? groupAdmin,
    String? locationAdmin,
    String? loginRequired,
    String? loginmethods,
    String? email,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUserDetails,
          [userId],
          {
            #firstName: firstName,
            #lastName: lastName,
            #addressLine1: addressLine1,
            #addressCity: addressCity,
            #addressPostcode: addressPostcode,
            #group: group,
            #location: location,
            #role: role,
            #language: language,
            #upass: upass,
            #title: title,
            #birthday: birthday,
            #nationality: nationality,
            #religion: religion,
            #ethnic: ethnic,
            #maritalStatus: maritalStatus,
            #ni: ni,
            #phoneLandline: phoneLandline,
            #phoneMobile: phoneMobile,
            #nokName: nokName,
            #nokPhone: nokPhone,
            #nokRelation: nokRelation,
            #addressLine2: addressLine2,
            #addressCounty: addressCounty,
            #addressCountry: addressCountry,
            #payrolCode: payrolCode,
            #notes: notes,
            #isActive: isActive,
            #exEmail: exEmail,
            #latitude: latitude,
            #longitude: longitude,
            #groupAdmin: groupAdmin,
            #locationAdmin: locationAdmin,
            #loginRequired: loginRequired,
            #loginmethods: loginmethods,
            #email: email,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postUserDetails,
            [userId],
            {
              #firstName: firstName,
              #lastName: lastName,
              #addressLine1: addressLine1,
              #addressCity: addressCity,
              #addressPostcode: addressPostcode,
              #group: group,
              #location: location,
              #role: role,
              #language: language,
              #upass: upass,
              #title: title,
              #birthday: birthday,
              #nationality: nationality,
              #religion: religion,
              #ethnic: ethnic,
              #maritalStatus: maritalStatus,
              #ni: ni,
              #phoneLandline: phoneLandline,
              #phoneMobile: phoneMobile,
              #nokName: nokName,
              #nokPhone: nokPhone,
              #nokRelation: nokRelation,
              #addressLine2: addressLine2,
              #addressCounty: addressCounty,
              #addressCountry: addressCountry,
              #payrolCode: payrolCode,
              #notes: notes,
              #isActive: isActive,
              #exEmail: exEmail,
              #latitude: latitude,
              #longitude: longitude,
              #groupAdmin: groupAdmin,
              #locationAdmin: locationAdmin,
              #loginRequired: loginRequired,
              #loginmethods: loginmethods,
              #email: email,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getDetails() => (super.noSuchMethod(
        Invocation.method(
          #getDetails,
          [],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getDetails,
            [],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postGroup({
    int? id,
    required String? name,
    required bool? active,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postGroup,
          [],
          {
            #id: id,
            #name: name,
            #active: active,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postGroup,
            [],
            {
              #id: id,
              #name: name,
              #active: active,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteGroup(int? groupid) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteGroup,
          [groupid],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteGroup,
            [groupid],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postJobTitle({
    int? id,
    required String? title,
    required bool? active,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postJobTitle,
          [],
          {
            #id: id,
            #title: title,
            #active: active,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postJobTitle,
            [],
            {
              #id: id,
              #title: title,
              #active: active,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteJobTitle(int? jobtitleid) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteJobTitle,
          [jobtitleid],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteJobTitle,
            [jobtitleid],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postQualif({
    int? id,
    String? comments,
    required String? title,
    required bool? active,
    required bool? levels,
    required bool? expire,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postQualif,
          [],
          {
            #id: id,
            #comments: comments,
            #title: title,
            #active: active,
            #levels: levels,
            #expire: expire,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postQualif,
            [],
            {
              #id: id,
              #comments: comments,
              #title: title,
              #active: active,
              #levels: levels,
              #expire: expire,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteQualification(
          int? qualificationid) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteQualification,
          [qualificationid],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteQualification,
            [qualificationid],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postWarehouse({
    int? id,
    String? contactEmail,
    required String? name,
    required String? contactName,
    required bool? active,
    required bool? sendReport,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postWarehouse,
          [],
          {
            #id: id,
            #contactEmail: contactEmail,
            #name: name,
            #contactName: contactName,
            #active: active,
            #sendReport: sendReport,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postWarehouse,
            [],
            {
              #id: id,
              #contactEmail: contactEmail,
              #name: name,
              #contactName: contactName,
              #active: active,
              #sendReport: sendReport,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteWarehouse(int? storageid) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteWarehouse,
          [storageid],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteWarehouse,
            [storageid],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postStorageItems({
    int? id,
    required String? name,
    required int? taxId,
    String? incomingPrice,
    String? outgoingPrice,
    required bool? service,
    required bool? active,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postStorageItems,
          [],
          {
            #id: id,
            #name: name,
            #taxId: taxId,
            #incomingPrice: incomingPrice,
            #outgoingPrice: outgoingPrice,
            #service: service,
            #active: active,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postStorageItems,
            [],
            {
              #id: id,
              #name: name,
              #taxId: taxId,
              #incomingPrice: incomingPrice,
              #outgoingPrice: outgoingPrice,
              #service: service,
              #active: active,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteStorageItems(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteStorageItems,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteStorageItems,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postHandoverTypes({
    int? id,
    required String? title,
    required bool? active,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postHandoverTypes,
          [],
          {
            #id: id,
            #title: title,
            #active: active,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postHandoverTypes,
            [],
            {
              #id: id,
              #title: title,
              #active: active,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteHandoverTypes(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteHandoverTypes,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteHandoverTypes,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteLocation(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLocation,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteLocation,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getChecklistTemplates(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChecklistTemplates,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getChecklistTemplates,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postChecklistTemplate({
    int? id,
    required String? name,
    required String? title,
    required bool? active,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postChecklistTemplate,
          [],
          {
            #id: id,
            #name: name,
            #title: title,
            #active: active,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postChecklistTemplate,
            [],
            {
              #id: id,
              #name: name,
              #title: title,
              #active: active,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postChecklistTemplateRoom({
    int? id,
    required String? name,
    required String? items,
    required bool? damages,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postChecklistTemplateRoom,
          [],
          {
            #id: id,
            #name: name,
            #items: items,
            #damages: damages,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postChecklistTemplateRoom,
            [],
            {
              #id: id,
              #name: name,
              #items: items,
              #damages: damages,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteChecklistTemplateRoom(
    int? id,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteChecklistTemplateRoom,
          [
            id,
            name,
          ],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteChecklistTemplateRoom,
            [
              id,
              name,
            ],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteProperty(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProperty,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteProperty,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postPropertie({
    int? id,
    required String? title,
    required int? locationId,
    required int? clientId,
    required int? storageId,
    required int? templateId,
    required String? startTime,
    required String? finishTime,
    String? startBreak,
    String? finishBreak,
    String? fpStartTime,
    String? fpFinishTime,
    String? fpStartBreak,
    String? fpFinishBreak,
    required bool? strictBreak,
    int? minWorkTime,
    int? minPaidTime,
    bool? splitTime,
    required bool? checklist,
    required bool? dayMon,
    required bool? dayTue,
    required bool? dayWed,
    required bool? dayThu,
    required bool? dayFri,
    required bool? daySat,
    required bool? daySun,
    required bool? active,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postPropertie,
          [],
          {
            #id: id,
            #title: title,
            #locationId: locationId,
            #clientId: clientId,
            #storageId: storageId,
            #templateId: templateId,
            #startTime: startTime,
            #finishTime: finishTime,
            #startBreak: startBreak,
            #finishBreak: finishBreak,
            #fpStartTime: fpStartTime,
            #fpFinishTime: fpFinishTime,
            #fpStartBreak: fpStartBreak,
            #fpFinishBreak: fpFinishBreak,
            #strictBreak: strictBreak,
            #minWorkTime: minWorkTime,
            #minPaidTime: minPaidTime,
            #splitTime: splitTime,
            #checklist: checklist,
            #dayMon: dayMon,
            #dayTue: dayTue,
            #dayWed: dayWed,
            #dayThu: dayThu,
            #dayFri: dayFri,
            #daySat: daySat,
            #daySun: daySun,
            #active: active,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postPropertie,
            [],
            {
              #id: id,
              #title: title,
              #locationId: locationId,
              #clientId: clientId,
              #storageId: storageId,
              #templateId: templateId,
              #startTime: startTime,
              #finishTime: finishTime,
              #startBreak: startBreak,
              #finishBreak: finishBreak,
              #fpStartTime: fpStartTime,
              #fpFinishTime: fpFinishTime,
              #fpStartBreak: fpStartBreak,
              #fpFinishBreak: fpFinishBreak,
              #strictBreak: strictBreak,
              #minWorkTime: minWorkTime,
              #minPaidTime: minPaidTime,
              #splitTime: splitTime,
              #checklist: checklist,
              #dayMon: dayMon,
              #dayTue: dayTue,
              #dayWed: dayWed,
              #dayThu: dayThu,
              #dayFri: dayFri,
              #daySat: daySat,
              #daySun: daySun,
              #active: active,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getPropertySpecialRate(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPropertySpecialRate,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getPropertySpecialRate,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postPropertySpecialRate({
    int? shiftId,
    required String? name,
    required double? rate,
    required int? minWorkTime,
    required int? minPaidTime,
    required bool? splitTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postPropertySpecialRate,
          [],
          {
            #shiftId: shiftId,
            #name: name,
            #rate: rate,
            #minWorkTime: minWorkTime,
            #minPaidTime: minPaidTime,
            #splitTime: splitTime,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postPropertySpecialRate,
            [],
            {
              #shiftId: shiftId,
              #name: name,
              #rate: rate,
              #minWorkTime: minWorkTime,
              #minPaidTime: minPaidTime,
              #splitTime: splitTime,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deletePropertySpecialRate(
    int? id,
    int? specialRateId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePropertySpecialRate,
          [
            id,
            specialRateId,
          ],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deletePropertySpecialRate,
            [
              id,
              specialRateId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getPropertyStaff(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPropertyStaff,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getPropertyStaff,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postPropertyStaff({
    int? id,
    required int? groupId,
    required int? numberOfStaff,
    int? maxOfStaff,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postPropertyStaff,
          [],
          {
            #id: id,
            #groupId: groupId,
            #numberOfStaff: numberOfStaff,
            #maxOfStaff: maxOfStaff,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postPropertyStaff,
            [],
            {
              #id: id,
              #groupId: groupId,
              #numberOfStaff: numberOfStaff,
              #maxOfStaff: maxOfStaff,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deletePropertyStaff(
    int? shiftId,
    int? groupId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePropertyStaff,
          [
            shiftId,
            groupId,
          ],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deletePropertyStaff,
            [
              shiftId,
              groupId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getPropertyQualification(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPropertyQualification,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getPropertyQualification,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postPropertyQualification({
    int? id,
    required int? qualificationId,
    required int? numberOfStaff,
    int? levelId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postPropertyQualification,
          [],
          {
            #id: id,
            #qualificationId: qualificationId,
            #numberOfStaff: numberOfStaff,
            #levelId: levelId,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postPropertyQualification,
            [],
            {
              #id: id,
              #qualificationId: qualificationId,
              #numberOfStaff: numberOfStaff,
              #levelId: levelId,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deletePropertyQualification(
    int? shiftId,
    int? qualificationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePropertyQualification,
          [
            shiftId,
            qualificationId,
          ],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deletePropertyQualification,
            [
              shiftId,
              qualificationId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getApprovals() => (super.noSuchMethod(
        Invocation.method(
          #getApprovals,
          [],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getApprovals,
            [],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postApprovals({
    required int? id,
    required bool? status,
    required String? comment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postApprovals,
          [],
          {
            #id: id,
            #status: status,
            #comment: comment,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postApprovals,
            [],
            {
              #id: id,
              #status: status,
              #comment: comment,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getStockList(int? warehouseId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStockList,
          [warehouseId],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getStockList,
            [warehouseId],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> approveUserQualification(
    int? userId, {
    required int? userqualificationId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #approveUserQualification,
          [userId],
          {#userqualificationId: userqualificationId},
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #approveUserQualification,
            [userId],
            {#userqualificationId: userqualificationId},
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postShiftRelease(
    int? allocationId, {
    required String? action,
    String? comment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postShiftRelease,
          [allocationId],
          {
            #action: action,
            #comment: comment,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postShiftRelease,
            [allocationId],
            {
              #action: action,
              #comment: comment,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getChecklists({
    required int? page,
    int? pageSize,
    String? filters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChecklists,
          [],
          {
            #page: page,
            #pageSize: pageSize,
            #filters: filters,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getChecklists,
            [],
            {
              #page: page,
              #pageSize: pageSize,
              #filters: filters,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getChecklistPdfs(
          {required String? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChecklistPdfs,
          [],
          {#id: id},
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getChecklistPdfs,
            [],
            {#id: id},
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getChecklistImages(
          {required String? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChecklistImages,
          [],
          {#id: id},
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getChecklistImages,
            [],
            {#id: id},
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getStockHistory({
    required int? storageid,
    required int? itemid,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStockHistory,
          [],
          {
            #storageid: storageid,
            #itemid: itemid,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getStockHistory,
            [],
            {
              #storageid: storageid,
              #itemid: itemid,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getAccountUserAvailability() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountUserAvailability,
          [],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getAccountUserAvailability,
            [],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> deleteAccountUserAvailability(
          String? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAccountUserAvailability,
          [date],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #deleteAccountUserAvailability,
            [date],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> createAccountUserAvailability({
    required String? startDate,
    required String? endDate,
    required bool? isFullDay,
    String? startTime,
    String? endTime,
    String? comment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAccountUserAvailability,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
            #isFullDay: isFullDay,
            #startTime: startTime,
            #endTime: endTime,
            #comment: comment,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #createAccountUserAvailability,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
              #isFullDay: isFullDay,
              #startTime: startTime,
              #endTime: endTime,
              #comment: comment,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> changeAccountPassword({
    required String? oldPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeAccountPassword,
          [],
          {
            #oldPassword: oldPassword,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #changeAccountPassword,
            [],
            {
              #oldPassword: oldPassword,
              #newPassword: newPassword,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> postCompanyDetails({
    required String? companyName,
    required String? domain,
    String? companyEmail,
    int? annualHolidayEntitlement,
    String? timezone,
    int? currencyId,
    String? logo,
    int? rotaLength,
    int? autoLogoutTime,
    int? lockingTime,
    int? autoSignOutTime,
    int? timeValidity,
    int? maxAttempts,
    int? colorSchemaId,
    int? annualHolidayEntitlementWeeks,
    int? holidayCalculationType,
    String? yearStart,
    int? paidSickness,
    int? periodOfIncapacity,
    int? minRest,
    int? lunchtime,
    int? lunchtimeUnpaid,
    int? rounding,
    int? gracePeriod,
    int? breaks,
    int? breakTime,
    int? breakTimeTotal,
    int? minHoursForLunch,
    String? lateReminders,
    String? longBreakReminders,
    String? signOutReminders,
    bool? isPhotoRequired,
    bool? isStrictLocation,
    int? undoTime,
    String? locale,
    bool? status,
    bool? showTitle,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postCompanyDetails,
          [],
          {
            #companyName: companyName,
            #domain: domain,
            #companyEmail: companyEmail,
            #annualHolidayEntitlement: annualHolidayEntitlement,
            #timezone: timezone,
            #currencyId: currencyId,
            #logo: logo,
            #rotaLength: rotaLength,
            #autoLogoutTime: autoLogoutTime,
            #lockingTime: lockingTime,
            #autoSignOutTime: autoSignOutTime,
            #timeValidity: timeValidity,
            #maxAttempts: maxAttempts,
            #colorSchemaId: colorSchemaId,
            #annualHolidayEntitlementWeeks: annualHolidayEntitlementWeeks,
            #holidayCalculationType: holidayCalculationType,
            #yearStart: yearStart,
            #paidSickness: paidSickness,
            #periodOfIncapacity: periodOfIncapacity,
            #minRest: minRest,
            #lunchtime: lunchtime,
            #lunchtimeUnpaid: lunchtimeUnpaid,
            #rounding: rounding,
            #gracePeriod: gracePeriod,
            #breaks: breaks,
            #breakTime: breakTime,
            #breakTimeTotal: breakTimeTotal,
            #minHoursForLunch: minHoursForLunch,
            #lateReminders: lateReminders,
            #longBreakReminders: longBreakReminders,
            #signOutReminders: signOutReminders,
            #isPhotoRequired: isPhotoRequired,
            #isStrictLocation: isStrictLocation,
            #undoTime: undoTime,
            #locale: locale,
            #status: status,
            #showTitle: showTitle,
          },
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #postCompanyDetails,
            [],
            {
              #companyName: companyName,
              #domain: domain,
              #companyEmail: companyEmail,
              #annualHolidayEntitlement: annualHolidayEntitlement,
              #timezone: timezone,
              #currencyId: currencyId,
              #logo: logo,
              #rotaLength: rotaLength,
              #autoLogoutTime: autoLogoutTime,
              #lockingTime: lockingTime,
              #autoSignOutTime: autoSignOutTime,
              #timeValidity: timeValidity,
              #maxAttempts: maxAttempts,
              #colorSchemaId: colorSchemaId,
              #annualHolidayEntitlementWeeks: annualHolidayEntitlementWeeks,
              #holidayCalculationType: holidayCalculationType,
              #yearStart: yearStart,
              #paidSickness: paidSickness,
              #periodOfIncapacity: periodOfIncapacity,
              #minRest: minRest,
              #lunchtime: lunchtime,
              #lunchtimeUnpaid: lunchtimeUnpaid,
              #rounding: rounding,
              #gracePeriod: gracePeriod,
              #breaks: breaks,
              #breakTime: breakTime,
              #breakTimeTotal: breakTimeTotal,
              #minHoursForLunch: minHoursForLunch,
              #lateReminders: lateReminders,
              #longBreakReminders: longBreakReminders,
              #signOutReminders: signOutReminders,
              #isPhotoRequired: isPhotoRequired,
              #isStrictLocation: isStrictLocation,
              #undoTime: undoTime,
              #locale: locale,
              #status: status,
              #showTitle: showTitle,
            },
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i4.Future<_i2.HttpResponse<dynamic>> getLanguages() => (super.noSuchMethod(
        Invocation.method(
          #getLanguages,
          [],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getLanguages,
            [],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<dynamic>>);
}
